### ISSUE TITLE
Exception not thrown when a Wish is edited to share the same name with another

### ISSUE THREAD

**Issue by leongshengmin** [CS2103-AY1819S1-T16-1/main#30]
Editing a wish to existing wish with the same name should throw an exception.

**Comment by bannified** [comment]
Currently, duplicated wishes are checked for with Wish::isSameWish method. This method compares the name, and price or email (should be deprecated).
Unlike Person, we might want to have duplicate Wish entries, as it is possible for a user to have two of the same item as wishes.

**Comment by leongshengmin** [comment]
Proposed solution: create a unique key (UID) for each `wish`. This will be set in the `Wish `model and be accessible by other classes. This UID will be used in place of the existing key (`Name `of a `wish`, which is non-unique) in the `wishMap `in the `WishTransaction `class.

**Comment by bannified** [comment]
With the addition of Wish's UUID in #66, we can use that property to differentiate between two different Wish objects.
