### ISSUE TITLE
As a user, I want to transfer money from one wish to another

### ISSUE THREAD

**Issue by bannified** [CS2103-AY1819S1-T16-1/main#51]
So that I can progress towards another wish faster.

**Comment by lionelat** [comment]
_MoveCommand_ is a command which reallocates money from one Wish to another.
MoveCommand can also be used to allocate/deallocate money from a Wish to a unusedFunds location, which is index 0.

Command Usage:
_move 2 1 200_ - moves $200 from the Wish at index 2 to the Wish at index 1.
_move 3 0 1001_ - moves $1001 from the Wish at index 3 to unusedFunds.
_move 0 3 1001_ - moves $1001 from unusedFunds to the Wish at index 3.

**Comment by bannified** [comment]
MoveCommand implemented in #89
