### ISSUE TITLE
Problem with Save Command and MoveCommand when input amount is a decimal value

### ISSUE THREAD

**Issue by lionelat** [CS2103-AY1819S1-T16-1/main#90]
Program raises an "Invalid Saved Amount" or "Invalid Command entered" message sometimes, when the amount entered is a decimal value.

**Comment by bannified** [comment]
Still not fixed.

Bug can still be reproduced by using saving an amount of 0.1 to any wish multiple times (usually 2-3 times will cause the bug to happen)

an example of the SaveCommand used to reproduce the bug:
`save 1 0.1`
